apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  template:
    metadata:
      name: api-gateway
      labels:
        app: api-gateway
    spec:
      containers:
        - image: kriola/fashionograf-api-gateway:6dbf207
          imagePullPolicy: IfNotPresent
          name: api-gateway-container
          envFrom:
            - configMapRef:
                name: api-gateway
          ports:
            - containerPort: 4000
              name: api-gateway
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 20
