apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fashionograf-api-gateway
spec:
  replicas: 1
  template:
    metadata:
      name: fashionograf-api-gateway
      labels:
        app: fashionograf-api-gateway
    spec:
      containers:
        - image: kriola/fashionograf-api-gateway:6dbf207
          imagePullPolicy: IfNotPresent
          name: fashionograf-api-gateway-container
          envFrom:
            - configMapRef:
                name: api-gateway-config
          ports:
            - containerPort: 4000
              name: fashionograf-api-gateway-port
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 4000
              initialDelaySeconds: 20
              periodSeconds: 20
