apiVersion: v1
kind: Service
metadata:
  name: fashionograf-api-gateway-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: fashionograf-api-gateway-port
      protocol: TCP
  selector:
    app: fashionograf-api-gateway
