apiVersion: v1
kind: Service
metadata:
  name: fashionograf-api-gateway-svc
spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30124
      protocol: TCP
  selector:
    app: fashionograf-api-gateway
